export const REDIS_KEYS = {
  FEED_ALL_IP_KEY: `feed:*:ip`,
  FEED_TREND_KEY: `feed:trend`,
  FEED_ORIGIN_TREND_KEY: 'feed:origin_trend',
  FEED_RECENT_ALL_KEY: 'feed:recent:*',
  FEED_RECENT_KEY: 'feed:recent',
  FEED_AI_QUEUE: `feed:ai:queue`,
  FEED_AI_RETRY_QUEUE: `feed:ai-retry:queue`,
  FEED_AI_RETRY_LOCK: `feed:ai-retry:lock`,
  USER_AUTH_KEY: 'signup',
  ADMIN_AUTH_KEY: 'auth',
  ADMIN_SESSION_BY_EMAIL: 'auth:email',
  ADMIN_INVALIDATED_PREFIX: 'admin:invalidated',
  ADMIN_REGISTER_KEY: 'admin:signup',
  ADMIN_DELETE_ACCOUNT_KEY: 'admin:delete-account',
  RSS_REMOVE_KEY: 'rss:remove',
  RSS_CERTIFICATION_KEY: 'rss:certification',
  CHAT_HISTORY_KEY: (roomId: string) => `chat:history:${roomId}`,
  FULL_FEED_CRAWL_QUEUE: `feed:full-crawl:queue`,
  USER_DELETE_ACCOUNT_KEY: 'user:delete-account',
  USER_RESET_PASSWORD_KEY: 'user:password_reset',
  USER_INVALIDATED_PREFIX: 'user:invalidated',
  OAUTH_PENDING_KEY: 'oauth:pending',
};
