FROM node:22-alpine AS builder

WORKDIR /var/web05-Denamu/feed-crawler

COPY ../package*.json ./

RUN npm ci

FROM node:22-alpine

WORKDIR /var/web05-Denamu/feed-crawler

COPY .. .

COPY --from=builder /var/web05-Denamu/feed-crawler/node_modules ./node_modules

RUN touch /var/log/feed-crawler.log

CMD ["sh", "-c", "npm run start:dev && tail -f /var/log/feed-crawler.log"]