FROM node:22-alpine AS builder

WORKDIR /var/web05-Denamu/feed-crawler

COPY . .

RUN npm ci

RUN npm run build

FROM node:22-alpine

WORKDIR /var/web05-Denamu/feed-crawler

COPY --from=builder /var/web05-Denamu/feed-crawler/dist ./dist
COPY --from=builder /var/web05-Denamu/feed-crawler/package.json .
COPY --from=builder /var/web05-Denamu/feed-crawler/node_modules ./node_modules
COPY --from=builder /var/web05-Denamu/feed-crawler/env ./env

CMD ["npm","run","start"]