/**
 * Feed-Crawler 로그 코드
 * Grafana에서 {code="FC_AI_SUMMARY_FAILURE"} 로 검색 가능
 */

// ==================== ERROR 코드 ====================
export const ErrorCodes = {
  // AI 관련
  FC_AI_SUMMARY_FAILURE: 'FC_AI_SUMMARY_FAILURE',
  FC_AI_API_ERROR: 'FC_AI_API_ERROR',
  FC_AI_PARSE_ERROR: 'FC_AI_PARSE_ERROR',
  FC_AI_REDIS_PARSE_ERROR: 'FC_AI_REDIS_PARSE_ERROR',

  // RSS 크롤링 관련
  FC_RSS_FETCH_ERROR: 'FC_RSS_FETCH_ERROR',
  FC_RSS_PARSE_ERROR: 'FC_RSS_PARSE_ERROR',
  FC_RSS_NOT_FOUND: 'FC_RSS_NOT_FOUND',

  // 피드 관련
  FC_FEED_ADD_ERROR: 'FC_FEED_ADD_ERROR',
  FC_FEED_ADD_FAILURE: 'FC_FEED_ADD_FAILURE',

  // 캐시/큐 관련
  FC_CACHE_DELETE_ERROR: 'FC_CACHE_DELETE_ERROR',
  FC_CACHE_SAVE_ERROR: 'FC_CACHE_SAVE_ERROR',
  FC_QUEUE_PUSH_ERROR: 'FC_QUEUE_PUSH_ERROR',

  // 인프라 관련
  FC_MYSQL_QUERY_ERROR: 'FC_MYSQL_QUERY_ERROR',
  FC_MYSQL_POOL_RELEASE_ERROR: 'FC_MYSQL_POOL_RELEASE_ERROR',
  FC_REDIS_OPERATION_ERROR: 'FC_REDIS_OPERATION_ERROR',
  FC_REDIS_PIPELINE_ERROR: 'FC_REDIS_PIPELINE_ERROR',
  FC_REDIS_CLOSE_ERROR: 'FC_REDIS_CLOSE_ERROR',
  FC_RABBITMQ_INIT_ERROR: 'FC_RABBITMQ_INIT_ERROR',
  FC_RABBITMQ_MESSAGE_ERROR: 'FC_RABBITMQ_MESSAGE_ERROR',

  // 기타
  FC_THUMBNAIL_EXTRACT_ERROR: 'FC_THUMBNAIL_EXTRACT_ERROR',
  FC_SCHEDULER_START_ERROR: 'FC_SCHEDULER_START_ERROR',
  FC_WORKER_PROCESS_ERROR: 'FC_WORKER_PROCESS_ERROR',
} as const;

// ==================== WARN 코드 ====================
export const WarnCodes = {
  FC_AI_SUMMARY_RETRY: 'FC_AI_SUMMARY_RETRY',
  FC_FEED_ADD_RETRY: 'FC_FEED_ADD_RETRY',
  FC_RSS_PARSE_WARN: 'FC_RSS_PARSE_WARN',
  FC_THUMBNAIL_EXTRACT_WARN: 'FC_THUMBNAIL_EXTRACT_WARN',
} as const;

// ==================== INFO 코드 ====================
export const InfoCodes = {
  // 스케줄러/Worker
  FC_SCHEDULER_START: 'FC_SCHEDULER_START',
  FC_CRAWL_START: 'FC_CRAWL_START',
  FC_CRAWL_COMPLETE: 'FC_CRAWL_COMPLETE',
  FC_WORKER_START: 'FC_WORKER_START',
  FC_WORKER_COMPLETE: 'FC_WORKER_COMPLETE',

  // AI 관련
  FC_AI_REQUEST: 'FC_AI_REQUEST',
  FC_AI_RESPONSE: 'FC_AI_RESPONSE',

  // RSS/Feed 관련
  FC_FULL_CRAWL_START: 'FC_FULL_CRAWL_START',
  FC_FULL_CRAWL_NO_REQUEST: 'FC_FULL_CRAWL_NO_REQUEST',
  FC_RSS_EMPTY: 'FC_RSS_EMPTY',
  FC_FEED_EMPTY: 'FC_FEED_EMPTY',
  FC_FEED_COUNT: 'FC_FEED_COUNT',
  FC_FEED_FOUND: 'FC_FEED_FOUND',
  FC_FEED_DUPLICATE_SKIP: 'FC_FEED_DUPLICATE_SKIP',

  // 캐시/큐 관련
  FC_CACHE_DELETE_SUCCESS: 'FC_CACHE_DELETE_SUCCESS',
  FC_CACHE_SAVE_SUCCESS: 'FC_CACHE_SAVE_SUCCESS',
  FC_QUEUE_PUSH_SUCCESS: 'FC_QUEUE_PUSH_SUCCESS',

  // 종료 관련
  FC_SHUTDOWN_SIGNAL: 'FC_SHUTDOWN_SIGNAL',
  FC_CONNECTIONS_CLOSED: 'FC_CONNECTIONS_CLOSED',

  // RabbitMQ
  FC_RABBITMQ_INIT_START: 'FC_RABBITMQ_INIT_START',
  FC_RABBITMQ_INIT_COMPLETE: 'FC_RABBITMQ_INIT_COMPLETE',

  // 기타
  FC_EXECUTION_TIME: 'FC_EXECUTION_TIME',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
export type WarnCode = (typeof WarnCodes)[keyof typeof WarnCodes];
export type InfoCode = (typeof InfoCodes)[keyof typeof InfoCodes];
