export const ErrorCodes = {
  // Email Service Errors
  EW_EMAIL_SEND_FAILURE: 'EW_EMAIL_SEND_FAILURE',
  EW_EMAIL_UNKNOWN_ERROR: 'EW_EMAIL_UNKNOWN_ERROR',

  // RabbitMQ Errors
  EW_RABBITMQ_CONSUME_ERROR: 'EW_RABBITMQ_CONSUME_ERROR',
  EW_RABBITMQ_INIT_ERROR: 'EW_RABBITMQ_INIT_ERROR',

  // Worker Errors
  EW_WORKER_START_FAILURE: 'EW_WORKER_START_FAILURE',
  EW_WORKER_SHUTDOWN_ERROR: 'EW_WORKER_SHUTDOWN_ERROR',
} as const;

export const WarnCodes = {
  // Consumer Warnings
  EW_CONSUMER_SHUTDOWN_SKIP: 'EW_CONSUMER_SHUTDOWN_SKIP',
  EW_CONSUMER_TIMEOUT: 'EW_CONSUMER_TIMEOUT',
} as const;

export const InfoCodes = {
  // Worker Lifecycle
  EW_WORKER_START: 'EW_WORKER_START',
  EW_WORKER_SHUTDOWN_SIGNAL: 'EW_WORKER_SHUTDOWN_SIGNAL',
  EW_WORKER_SHUTDOWN_COMPLETE: 'EW_WORKER_SHUTDOWN_COMPLETE',

  // RabbitMQ
  EW_RABBITMQ_INIT_START: 'EW_RABBITMQ_INIT_START',
  EW_RABBITMQ_INIT_COMPLETE: 'EW_RABBITMQ_INIT_COMPLETE',
  EW_RABBITMQ_CONSUMER_START: 'EW_RABBITMQ_CONSUMER_START',
  EW_RABBITMQ_DISCONNECT: 'EW_RABBITMQ_DISCONNECT',
  EW_RABBITMQ_MSG_RETURN: 'EW_RABBITMQ_MSG_RETURN',

  // Consumer
  EW_CONSUMER_START: 'EW_CONSUMER_START',
  EW_CONSUMER_LISTENING: 'EW_CONSUMER_LISTENING',
  EW_CONSUMER_CLOSE: 'EW_CONSUMER_CLOSE',
  EW_CONSUMER_STOP: 'EW_CONSUMER_STOP',
  EW_CONSUMER_TASK_START: 'EW_CONSUMER_TASK_START',
  EW_CONSUMER_TASK_COMPLETE: 'EW_CONSUMER_TASK_COMPLETE',
  EW_CONSUMER_TASK_REMAINING: 'EW_CONSUMER_TASK_REMAINING',
  EW_CONSUMER_NO_PENDING: 'EW_CONSUMER_NO_PENDING',
  EW_CONSUMER_WAIT_PENDING: 'EW_CONSUMER_WAIT_PENDING',
  EW_CONSUMER_ALL_COMPLETE: 'EW_CONSUMER_ALL_COMPLETE',
  EW_CONSUMER_STOP_RECEIVE: 'EW_CONSUMER_STOP_RECEIVE',
  EW_CONSUMER_WAIT_TASKS: 'EW_CONSUMER_WAIT_TASKS',
  EW_CONSUMER_CLEANUP: 'EW_CONSUMER_CLEANUP',

  // Email
  EW_EMAIL_SEND_SUCCESS: 'EW_EMAIL_SEND_SUCCESS',
  EW_EMAIL_TYPE_UNKNOWN: 'EW_EMAIL_TYPE_UNKNOWN',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
export type WarnCode = (typeof WarnCodes)[keyof typeof WarnCodes];
export type InfoCode = (typeof InfoCodes)[keyof typeof InfoCodes];
