FROM alpine:latest AS builder

RUN apk add --no-cache dos2unix
RUN mkdir -p /etc/nginx/scripts

# 스크립트 파일을 컨테이너에 복사
COPY ./scripts /etc/nginx/scripts

RUN dos2unix /etc/nginx/scripts/generate_cert.sh

FROM nginx:stable-alpine

COPY --from=builder /etc/nginx/scripts /etc/nginx/scripts
RUN apk add --no-cache openssl
RUN sh /etc/nginx/scripts/generate_cert.sh

CMD ["nginx", "-g", "daemon off;"]