FROM node:22-alpine AS builder

WORKDIR /var/web05-Denamu/email-worker

COPY package*.json ./

RUN npm ci

FROM node:22-alpine

WORKDIR /var/web05-Denamu/email-worker

COPY --from=builder /var/web05-Denamu/email-worker/node_modules ./node_modules

CMD ["npm","run","start:dev"]