FROM node:22-alpine AS builder

WORKDIR /var/web05-Denamu/server

COPY ../package*.json ./

RUN npm ci

FROM node:22-alpine

WORKDIR /var/web05-Denamu/server

COPY .. .

COPY --from=builder /var/web05-Denamu/server/node_modules ./node_modules

CMD ["npm","run","start:dev"]