export enum FileUploadType {
  PROFILE_IMAGE = 'PROFILE_IMAGE',
  BOARD_IMAGE = 'BOARD_IMAGE',
  MARKETING_EMAIL_IMAGE = 'MARKETING_EMAIL_IMAGE',
}

export const ADMIN_UPLOADABLE_IMAGE_TYPES = [
  FileUploadType.BOARD_IMAGE,
  FileUploadType.MARKETING_EMAIL_IMAGE,
] as const;

export const FILE_SIZE_LIMITS = {
  // MB 단위
  IMAGE: 5 * 1024 * 1024,
  DEFAULT: 10 * 1024 * 1024,
};

export const IMAGE_WEBP_QUALITY = 80;

export const ORPHAN_FILE_GRACE_PERIOD_MS = 1000 * 60 * 60 * 24;
