FROM node:22-alpine AS builder

WORKDIR /var/web05-Denamu/client

COPY ./client .

RUN npm ci

RUN npm run build

FROM nginx:1.18.0

WORKDIR /var/web05-Denamu/client

COPY --from=builder /var/web05-Denamu/client/dist /var/web05-Denamu/client/dist
COPY ../../static /var/web05-Denamu/static

COPY ../../nginx/scripts /etc/nginx/scripts
COPY ../../nginx/nginx.conf /etc/nginx/nginx.conf

RUN sh "/etc/nginx/scripts/generate_cert.sh"

CMD ["nginx","-g","daemon off;"]