export const EmailPayloadConstant = {
  USER_CERTIFICATION: 'userCertification',
  RSS_REMOVAL: 'rssRemoval',
  RSS_CERTIFICATION: 'rssCertification',
  RSS_REGISTRATION: 'rssRegistration',
  RSS_REGISTRATION_REQUEST: 'rssRegistrationRequest',
  PASSWORD_RESET: 'passwordReset',
  ACCOUNT_DELETION: 'accountDeletion',
  ADMIN_CERTIFICATION: 'adminCertification',
  ADMIN_ACCOUNT_DELETION: 'adminAccountDeletion',
  ADMIN_PASSWORD_RESET: 'adminPasswordReset',
  QNA_ANSWERED: 'qnaAnswered',
  NOTICE_PUBLISHED: 'noticePublished',
  MARKETING_BROADCAST: 'marketingBroadcast',
} as const;
