name: BE DTO Test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      # 1. 현재 PR 브랜치로 체크아웃 하기
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      # 2. Node.js 환경 설정
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      # 3. 의존성 설치
      - name: Install dependencies
        working-directory: ./server
        run: npm ci

      # 4. DTO 테스트 실행
      - name: Run DTO Test
        working-directory: ./server
        run: npm run test:dto

      # TODO: 테스트 커버리지, 혹은 테스트 로그 커멘트 작성 로직 추가하기
